import { useState } from "react";
import { BookOpen, Shield, Cpu, Eye, Zap, Layers, Languages, ScrollText } from "lucide-react";
import ScrollRevealWrapper from "@/components/ScrollRevealWrapper";

const articles = [
  { title: { en: "Information Governance in the AI Era", es: "Gobernanza de la Información en la Era de la IA" }, tag: "Governance", icon: Shield, content: { en: "AI-generated outputs, automated decisions, and model lineage should be treated as auditable information assets. Governance must be designed into the workflow, not attached after the fact.", es: "Las salidas de IA, las decisiones automatizadas y la trazabilidad de los modelos deben tratarse como activos de información auditables. La gobernanza debe diseñarse dentro del flujo de trabajo." }, takeaway: { en: "Governance is architecture.", es: "La gobernanza es arquitectura." } },
  { title: { en: "The Aesthetics of Order", es: "La Estética del Orden" }, tag: "Systems thinking", icon: Eye, content: { en: "From archival description to database design, well-structured systems reduce friction because every element has a clear place, purpose, and relationship to the whole.", es: "Desde la descripción archivística hasta el diseño de bases de datos, los sistemas bien estructurados reducen la fricción porque cada elemento tiene un lugar, propósito y relación claros." }, takeaway: { en: "Clarity is a performance advantage.", es: "La claridad es una ventaja operativa." } },
  { title: { en: "Kaizen in Digital Operations", es: "Kaizen en Operaciones Digitales" }, tag: "Process", icon: Zap, content: { en: "Operational excellence compounds through small, observable improvements: refine one step, automate one bottleneck, and make one metric more reliable.", es: "La excelencia operacional se acumula mediante mejoras pequeñas y observables: refinar un paso, automatizar un cuello de botella y hacer más confiable una métrica." }, takeaway: { en: "Small improvements become infrastructure.", es: "Las mejoras pequeñas se convierten en infraestructura." } },
  { title: { en: "AI-Assisted Building for Domain Experts", es: "Construcción asistida por IA para expertos de dominio" }, tag: "AI & tools", icon: Cpu, content: { en: "LLM-assisted development lets operations professionals translate domain knowledge into useful internal tools while keeping human judgment, testing, and documentation in the loop.", es: "El desarrollo asistido por LLM permite que profesionales de operaciones conviertan conocimiento de dominio en herramientas internas útiles, manteniendo el juicio humano, las pruebas y la documentación." }, takeaway: { en: "Domain knowledge becomes leverage.", es: "El conocimiento de dominio se convierte en capacidad." } },
  { title: { en: "Compliance as Architecture", es: "Cumplimiento como Arquitectura" }, tag: "Regulated operations", icon: Layers, content: { en: "In healthcare, financial, and legal environments, the strongest compliance controls are embedded in workflow design and made visible through records, permissions, and audit trails.", es: "En entornos de salud, finanzas y legal, los controles más sólidos están integrados en el diseño del flujo y se hacen visibles mediante registros, permisos y trazabilidad." }, takeaway: { en: "Good compliance guides behavior naturally.", es: "El buen cumplimiento guía la conducta de forma natural." } },
  { title: { en: "The Menderist Working Thesis", es: "La Tesis de Trabajo Menderista" }, tag: "Independent research", icon: ScrollText, content: { en: "A working research framework on order, evidence, continuity, and the responsible use of technology. It informs my practice without replacing professional standards or empirical review.", es: "Un marco de investigación sobre orden, evidencia, continuidad y uso responsable de la tecnología. Informa mi práctica sin sustituir los estándares profesionales ni la revisión empírica." }, takeaway: { en: "The past illuminates the future.", es: "El pasado ilumina el porvenir." } },
];

const AtheneumSection = () => {
  const [lang, setLang] = useState<"en" | "es">("en");
  return (
    <section id="atheneum" className="py-6 md:py-10 bg-stone-dark relative energy-beams">
      <div className="energy-beam-extra" /><div className="energy-beam-extra-2" />
      <div className="absolute inset-0 bg-gradient-to-b from-background/50 via-transparent to-background/50 pointer-events-none" />
      <ScrollRevealWrapper className="container mx-auto px-4 max-w-6xl relative">
        <div className="flex items-end justify-between mb-1"><div><h2 className="font-serif text-3xl md:text-4xl text-bone glitch-hover inline-block">Knowledge &amp; Research</h2><p className="font-mono text-xs tracking-[0.2em] uppercase neon-text-cyan mt-1">Professional notes · independent inquiry</p></div><button onClick={() => setLang(lang === "en" ? "es" : "en")} className="flex items-center gap-2 px-3 py-1.5 border border-border rounded-sm font-mono text-[10px] tracking-wider uppercase text-bone-dim hover:text-accent hover:border-accent transition-all" title="Toggle language"><Languages size={12} />{lang === "en" ? "ES" : "EN"}</button></div>
        <p className="max-w-3xl text-sm text-bone-dim leading-relaxed mt-4 mb-5">{lang === "en" ? "A concise working library on information, systems, governance, and the responsible conversion of knowledge into capability." : "Una biblioteca de trabajo sobre información, sistemas, gobernanza y la conversión responsable del conocimiento en capacidad."}</p>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{articles.map((a) => { const Icon = a.icon; return <article key={a.title.en} className="group glass-card p-4 rounded-sm flex flex-col circuit-border"><div className="flex items-center gap-3 mb-4"><Icon size={18} className="neon-text-cyan shrink-0" /><span className="font-mono text-[10px] tracking-[0.2em] uppercase text-bone-dim">{a.tag}</span></div><h3 className="font-serif text-lg text-bone mb-3 group-hover:neon-text-gold transition-colors duration-300 glitch-hover">{a.title[lang]}</h3><p className="text-xs text-bone-dim leading-relaxed mb-3 flex-1">{a.content[lang]}</p><div className="border-t border-border pt-3 mt-auto"><p className="font-mono text-[10px] tracking-wider uppercase neon-text-cyan">▸ {a.takeaway[lang]}</p></div></article>; })}</div>
      </ScrollRevealWrapper>
    </section>
  );
};
export default AtheneumSection;

